[package]
name = "tiny-shrooms"
version = "0.0.1"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "macos-private-api", "image-png"] }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
objc2-app-kit = { version = "0.3", default-features = false, features = ["std", "NSWorkspace"] }
objc2-foundation = { version = "0.3", default-features = false, features = ["std", "block2", "NSNotification", "NSOperation", "NSString"] }
